import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css';
import {ToastContainer} from "react-toastify";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="h-full w-full">
        <body className={`${inter.className} h-full w-full`}
        >
        <ToastContainer/>
        {children}
        </body>
        </html>
    )
}
